[[RouteExchangeModel]]
== Route Exchange Model

=== Overview

This document specifies a single encoding of the Route model described in the previous clause for the creation and transfer of route information between a variety of routing components ("Route Exchange Model"). The encoding uses https://geojson.org/[GeoJSON] to represent routes according to the model described above and is defined in the next clause. 

A GeoJSON feature collection is used to represent the Route. Each RouteComponent is represented by a GeoJSON feature in the feature collection of the route. 

GeoJSON is used for the following reasons:

* lightweight
* extensible
* widely supported in libraries and tools
* consistent with the emerging https://www.ogcapi.ogc.org/[OGC API standards]
* an https://tools.ietf.org/html/rfc7946[open standard]

[[rc_rem]]
=== Requirements class "Route Exchange Model"

This requirement class states requirements that apply to all representations of a route.

See <<rem-example-full>> for an example of a route.

The normative statements use JSON Schema to specify schema components.

[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/rem/1.0/req/rem
|Target type |JSON object
|Dependency |link:https://tools.ietf.org/rfc/rfc7946.txt[GeoJSON]
|Dependency |link:https://tools.ietf.org/rfc/rfc3339.txt[Date and Time on the Internet: Timestamps]
|===

[[req_rem_geojson]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/rem/geojson*
^|A |Every representation of a route or route component SHALL be a valid GeoJSON object.
|===

[[req_rem_date-time]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/rem/date-time*
^|A |Every representation of a timestamp SHALL be a valid `date-time` value according to link:https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339, 5.6].
|===

[[req_rem_fc]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/rem/fc*
^|A |The representation of a route SHALL be a valid GeoJSON feature collection.
|===

[[rec_rem_fc-name]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/rem/fc-name*
^|A |The feature collection SHOULD have a member with the name "name" that is a title of the route with the following schema:

[source,JSON]
----
{
  "type": "string"
}
----
|===

Typically the name will be provided by the requester of the route.

[[req_rem_fc-features]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/rem/fc-features*
^|A |The feature collection SHALL contain the following features:

* a route overview
* the start point of the route
* the end point of the route
* one or more segments
^|B |The sequence of the segments SHALL be in their order along the route.
|===

[[rec_rem_fc-links]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/rem/fc-links*
^|A |The feature collection SHOULD have a member with the name "links" with the following schema:

[source,JSON]
----
{
  "type": "array",
  "items": {
    "type": "object",
    "required": [ "rel", "href" ],
    "properties": {
      "href": { "type": "string" },
      "rel": { "type": "string" },
      "type": { "type": "string" },
      "hreflang": { "type": "string" },
      "title": { "type": "string" }
    }
  }
}
----
^|B |There SHOULD be a link with

* `rel` with value `self`;
* `type` with value `application/geo+json`;
*  a URI to fetch the route in `href`.
^|C |There SHOULD be a link with

* `rel` with value `describedby`;
* `type` with value `application/json`;
*  a URI to fetch information about the definition of the route (start and end point, constraints) in `href`.
^|D |There SHOULD be a link with

* `rel` with value `describedby`;
* `type` with value `application/schema+json`;
*  a URI to fetch the JSON Schema of the route in `href`.
|===

[[req_rem_start]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/rem/start*
^|A |The start point of the route SHALL be a GeoJSON feature with a Point geometry.
^|B |The feature SHALL have a property `featureType` with the value `start`.
^|C |The point geometry of the feature SHALL be identical to the first point of the route overview.
^|D |If the feature has a property `timestamp`, it SHALL be of type `string`, format `date-time`, and indicate the (estimated) departure time.
|===

[[req_rem_end]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/rem/end*
^|A |The end point of the route SHALL be a GeoJSON feature with a Point geometry.
^|B |The feature SHALL have a property `featureType` with the value `end`.
^|C |The point geometry of the feature SHALL be identical to the last point of the route overview and identical to the point in the last segment.
^|D |If the feature has a property `timestamp`, it SHALL be of type `string`, format `date-time`, and indicate the (estimated) arrival time.
|===

[[req_rem_overview]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/rem/overview*
^|A |The route overview SHALL be a GeoJSON feature with a LineString geometry.
^|B |The feature SHALL have a property `type` with the value `overview`.
^|C |The line string geometry of the feature SHALL be the path from the start point to the end point of the route.
^|D |The feature SHALL have a property `length_m` (type: `number`) with the length of the segment (in meters).
^|E |The feature SHALL have a property `duration_s` (type: `number`) with the estimated amount of time required to travel the segment (in seconds).
^|F |If the feature has a property `maxHeight_m`, the value SHALL be of type `number` with a known height restriction on the route (in meters).
^|G |If the feature has a property `maxWeight_t`, the value SHALL be of type `number` with a known weight restriction on the route (in tons).
^|H |If the feature has a property `obstacles`, the value SHALL be of type `string` and describe how obstacles were taken into account in the route calculation.
^|I |If the feature has a property `processingTime`, it SHALL be a `date-time` as specified by link:https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339, 5.6] and state the time when the route was calculated.
^|J |If the feature has a property `comment`, the value SHALL be of type `string` and explain any minor issues that were encountered during the processing of the routing request, i.e. any issues that did not result in an error.
|===

[[rec_rem_overview-properties]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/rem/overview-properties*
^|A |The route overview SHOULD have the property `processingTime`.
^|B |If the process that creates the route has access to the information, the route overview SHOULD have the properties `maxHeight_m`, `maxWeight_t`, and `obstacles`.
|===

[[req_rem_segments]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/rem/segments*
^|A |Each segment of the route SHALL be a GeoJSON feature with a Point geometry.
^|B |The segment feature SHALL have a property `type` with the value `segment`.
^|C |The point geometry of the feature SHALL be the last position of the segment and be on the line string geometry of the route overview.
^|D |The feature SHALL have a property `length_m` (type: `number`) with the length of the segment (in meters).
^|E |The feature SHALL have a property `duration_s` (type: `number`) with the estimated amount of time required to travel the segment (in seconds).
^|F |The sum of all `length_m` values of segments SHALL be identical to the `length_m` value in the route overview.
^|G |The sum of all `duration_s` values of segments SHALL be identical to the `duration_s` value in the route overview.
^|H |If the feature has a property `maxHeight_m`, the value SHALL be of type `number` with a known height restriction on the segment (in meters).
^|I |If the feature has a property `maxWeight_t`, the value SHALL be of type `number` with a known weight restriction on the segment (in tons).
^|J |If the feature has a property `speedLimit`, the value SHALL be of type `integer` with a known speed limit on the segment.
^|K |If the feature has a property `speedLimit`, the unit of the speed limit SHALL be specified in a property `speedLimitUnit`; the allowed values are `kmph` (kilometers per hour) and `mph` (miles per hour).
^|L |If the feature has a property `roadName`, the value SHALL be of type `string` with the road/street name of the segment.
^|M |If the feature has a property `roadName` and the feature is part of a response to a HTTP(S) request, the language SHALL be specified in the `Content-Language` header.
^|N |If the feature has a property `instructions`, the value SHALL be of type `string` with an instruction for the maneuver at the end of the segment. Allowed values are `continue`, `left` and `right`.
|===
