[[processes-profile]]
== Routing API as a profile of _OGC API - Processes_

This clause specifies a second API option for a Routing API that supports more-or-less the same capabilities as the Routing API defined in the previous clause and re-uses the Route Exchange Model. However, it is based on the _OGC API - Processes_ standards and is defined as a profile of that standard.

NOTE: See https://github.com/opengeospatial/ogcapi-routes/issues/15[open issue #15].

NOTE: This option is to a large extent specified by the _OGC API - Processes_ candidate standard. It has additional requirements and conformance classes that mirror the ones from the first option. To avoid a lot of repetition, this clause currently does not define each of these classes formally like for the first option, but describes how each class of the first option is mapped to the _OGC API - Processes_ option.

=== Overview

The profile has the following characteristics:

* The resources are processes and jobs, consistent with the
_OGC API - Processes_ draft.
* The input to routing tasks (jobs) will be the start and end location
plus optional routing parameters (intermediate waypoints, constraints,
etc.), based on the route definition schema specified above.
* The output / result of routing tasks is using the Route
Exchange Model in GeoJSON.

Note that one characteristic of this API option is that the input/output
descriptions as part of the processOffering schema add an additional
schema layer and describe another (OGC API - Proceses-specific) schema description language
in addition to the JSON schema description in the OpenAPI definition. This
also has the effect, that the schema of the routing parameters is
not part of the API definition, but described as a response to a
process resource in the API (`/processes/routing`).

The following table provides an overview of the resources. For details
see the draft _OGC API - Processes_ specification.

Note that the OGC API Common requirements apply to this option, too.

[#tldroaproc,reftext='{table-caption} {counter:table-num}']
.Overview of resources and applicable HTTP methods in the _OGC API - Processes_ profile
[cols="32,25,10,33",options="header"]
!===
|Resource |Path |HTTP method |Document reference
|Landing page |`/` |GET |<<oaproc_landing_page>>
|Conformance declaration |`/conformance` |GET |<<oaproc_conformance>>
|Processes |`/processes` |GET |<<oaproc_processes>>
|Process |`/processes/routing` |GET |<<oaproc_process>>
.2+|Jobs .2+|`/jobs` |GET |<<oaproc_jobs>>
|POST |<<oaproc_new_job>>
|Job |`/jobs/{jobId}` |GET |<<oaproc_job_status>>
|Result |`/jobs/{jobId}/results` |GET |<<oaproc_result>>
!===

NOTE: Proposal being discussed ( https://github.com/opengeospatial/ogcapi-processes/issues/124 ) to POST execution request to `/processes/{processId}` instead of to `/jobs`.
If we manage to fully harmonize the Processes / `/routes` approach, `/routes` could be an alias to `/processes/routing` supporting same POST requests.

[[oaproc_landing_page]]
=== Landing page

See <<landing_page>>, except that the "data" link references `/processes`.

[[oaproc_conformance]]
=== Conformance declaration

The following is an example of the conformance declaration for the _OGC API - Processes_ option
that implements all requirements classes. The ResultSet class has no equivalent functionality with _OGC API - Processes_.

[[example_oaproc_cc]]
.Conformance declaration
=================
[source,JSON]
----
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/json",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/oas30",
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/ogc-process-description",
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/job-list",
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/callback",
    "http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/dismiss",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0/conf/oaproc-routing",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0/conf/intermediate-waypoints",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0/conf/max-height",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0/conf/max-weight",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0/conf/obstacles",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0/conf/routing-engine",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0/conf/routing-algorithm",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0/conf/source-dataset",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0/conf/time"
  ]
}
----

The following describes the _OGC API - Processes_ conformance classes
equivalent to the Routing API options:

* Delete route: If a route was computed asynchronously, it gets a `jobId` for which the http://docs.opengeospatial.org/DRAFTS/18-062.html#Dismiss[_Dismiss_] conformance class can be used to delete the job and results (DELETE on `/jobs/{jobId}`)
* Callback: See _OGC API - Processes_ http://docs.opengeospatial.org/DRAFTS/18-062.html#Callbacks[_Callback_ conformance class]
* Synchronous execution is available with `"mode" : "sync"`

=================

[[oaproc_processes]]
=== List processes

A process with id 'routing' is included in the list of processes available according to the link:https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/processList.yaml[process list schema].

[[example_oaproc_processes]]
.List of processes
=================
[source,JSON]
----
{
  "processes": [ {
    "id": "routing",
    "title": "Compute routes",
    "description": "The process computes and creates a new route.

 At a minimum, a route is defined by two `waypoints`, the start and end
 point of the route.

 Every process supports at least 'fastest' and 'shortest' as the
 routing `preference`. The default value is 'fastest'.

An optional `name` for the route may be provided. The name will be
used as the title in links to the route and also included in the route
itself.

More parameters and routing constraints can optionally be provided
with the routing request:
* Source dataset to use when processing the route
* Routing engine to use when processing the route
* Routing algorithm to use when processing the route
* Obstacle requirements
* Height restriction
* Weight restriction
* Time of departure or arrival",
    "keywords": [ "routing" ],
    "version": "1.0",
    "jobControlOptions": [ "async-execute","sync-execute" ],
    "outputTransmission": [ "value","reference" ],
    "links": [ {
      "href": "https://example.org/api/ogcapi/v1/processes/routing",
      "rel": "???",
      "title": "execution endpoint"
    } ]
  } ]
}
----
=================

[[oaproc_process]]
=== Describe routing process

A description of the process with id 'routing' is returned according to the link:https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/process.yaml[OGC process description schema].

The `inputs` member will include all parameters that the _OGC API - Processes_ profile supports
according to the declared conformance classes.

NOTE: We are still trying to simplify process description in _OGC API - Processes_, potentially even align some pieces better with JSON Schema? (https://github.com/opengeospatial/ogcapi-processes/issues/122)

[[example_oaproc_process]]
.Process description
=================
[source,JSON]
----
{
  "inputs": [
    {
      "id": "waypoints",
      "title": "Waypoints",
      "description": "A list of points along the route. At least two points have to be provided (start and end point).",
      "formats": [
        {
          "mediaType": "application/geo+json",
          "schema": "https://geojson.org/schema/MultiPoint.json"
        }
      ],
      "minOccurs": 1,
      "maxOccurs": 1
    },
    {
      "id": "preference",
      "title": "Routing preference",
      "description": "The routing preference.",
      "formats": [
        {
          "mediaType": "text/plain"
        }
      ],
      "literalDataDomain": {
        "dataType": "string",
        "defaultValue": "fastest",
        "allowedValues": [
          "fastest",
          "shortest"
        ]
      },
      "minOccurs": 0,
      "maxOccurs": 1
    },
    {
      "id": "maxHeight",
      "title": "Maximum height",
      "description": "A height restriction for vehicles in meters \nto consider when computing the route.\n\nSupport for this parameter is not required and the parameter may be\nremoved from the API definition.",
      "formats": [
        {
          "mediaType": "text/plain"
        }
      ],
      "literalDataDomain": {
        "dataType": "double",
        "uom": {
          "name": "meter"
        }
      },
      "minOccurs": 0,
      "maxOccurs": 1
    },
    {
      "id": "maxWeight",
      "title": "Maximum weight",
      "description": "A weight restriction for vehicles in tons \nto consider when computing the route.\n\nSupport for this parameter is not required and the parameter may be\nremoved from the API definition.",
      "formats": [
        {
          "mediaType": "text/plain"
        }
      ],
      "literalDataDomain": {
        "dataType": "double",
        "uom": {
          "name": "tons"
        }
      },
      "minOccurs": 0,
      "maxOccurs": 1
    },
    {
      "id": "obstacle",
      "title": "???",
      "description": "???.",
      "formats": [
        {
          "mediaType": "text/plain"
        }
      ],
      "literalDataDomain": {
        "dataType": "string",
        "defaultValue": "???",
        "allowedValues": [
          "???"
        ]
      },
      "minOccurs": 0,
      "maxOccurs": 1
    },
    {
      "id": "dataset",
      "title": "source dataset",
      "description": "The source dataset to use for calculating the route.",
      "formats": [
        {
          "mediaType": "text/plain"
        }
      ],
      "literalDataDomain": {
        "dataType": "string",
        "allowedValues": [
          "NSG",
          "OSM",
          "HERE"
        ]
      },
      "minOccurs": 0,
      "maxOccurs": 1
    },
    {
      "id": "engine",
      "title": "routing engine",
      "description": "The routing engine to use for calculating the route.",
      "formats": [
        {
          "mediaType": "text/plain"
        }
      ],
      "literalDataDomain": {
        "dataType": "string",
        "allowedValues": [
          "Skymantics",
          "Ecere",
          "HERE"
        ]
      },
      "minOccurs": 0,
      "maxOccurs": 1
    },
    {
      "id": "algorithm",
      "title": "graph solving algorithm",
      "description": "The routing / graph solving algorithm to use for calculating the route.",
      "formats": [
        {
          "mediaType": "text/plain"
        }
      ],
      "literalDataDomain": {
        "dataType": "string",
        "defaultValue": "Dikjstra",
        "allowedValues": [
          "Dikjstra",
          "Floyd Marshall",
          "A*"
        ]
      },
      "minOccurs": 0,
      "maxOccurs": 1
    },
    {
      "id": "when",
      "title": "time of departure or arrival",
      "description": "The time of departure or arrival. Default is \"now\".",
      "formats": [
        {
          "mediaType": "text/plain"
        }
      ],
      "literalDataDomain": {
        "dataType": "dateTime"
      },
      "minOccurs": 0,
      "maxOccurs": 1
    },
    {
      "id": "deparr",
      "title": "departure",
      "description": "Specifies whether the value of `when` refers to the\ntime of departure or arrival. Default is departure.",
      "formats": [
        {
          "mediaType": "text/plain"
        }
      ],
      "literalDataDomain": {
        "dataType": "string",
        "defaultValue": "departure",
        "allowedValues": [
          "departure",
          "arrival"
        ]
      },
      "minOccurs": 0,
      "maxOccurs": 1
    }
  ],
  "outputs": [
    {
      "id": "route",
      "title": "the route",
      "description": "The route is represented by a GeoJSON feature collection\nthat contains the following information:\n\n* A `name`, if one was provided with the route definition.\n* A link to the canonical URI of the route and its definition\n(link relations `self` and `describedBy`)\n* An array of features (the properties of each is to be decided)\n* The route overview feature. This has a LineString \ngeometry of the complete route from start to end location.\n* The start point of the route with a Point geometry.\n* A feature for every segment of the route. This has a \nLineString geometry starting at the end of the previous \nsegment (or, for the first segment, the start point).\n* The end point of the route with a Point geometry.",
      "formats": [
        {
          "mediaType": "application/geo+json",
          "schema": "https://geojson.org/schema/FeatureCollection.json",
          "default": true
        }
      ]
    }
  ]
}
----
=================

[[oaproc_jobs]]
=== List routing jobs

This operation just returns an object with a `jobs` member, which is an
array of existing `jobId` values.

[[oaproc_new_job]]
=== Compute new route

This operation creates a new route. It is similar to the request in the
Routing API option, except that the input/output descriptions according
to _OGC API - Processes_ are used.

NOTE: Ideally, _OGC API - Processes_ would allow `output`, `response` and `mode` to all be optional and default to these values without having to specify them.

[[example_oaproc_new_job]]
.New route
=================
[source,JSON]
----
{
  "inputs": {
    "waypoints" :
    {
      "format": { "mediaType": "application/geo+json" },
      "value": {
       "type": "MultiPoint",
       "coordinates": [
         [ 36.1234515, 32.6453783 ],
         [ 36.1214698, 32.655952  ],
         [ 36.1247213, 32.7106286 ]
       ]
      }
    },
    "preference" : { "value": "fastest" },
    "maxHeight" : { "value": 4.5, "uom": { "name": "meter" } },
  },
  "outputs": {
    "route" :
    {
      "output": { "format": { "mediaType": "application/geo+json" } },
      "transmissionMode": "value"
    }
  },
  "response" : "document",
  "mode" : "async"
}
----
=================

[[oaproc_job_status]]
=== Query routing job status

This operation informs about the status of the job with id `jobId`. It returns
the status plus optionally a message and a progress estimate in percent.

The Routing API option currently does not support the message and the percent
estimate.

[[oaproc_result]]
=== Retrieve route

The route according to the Route Exchange Model is returned, wrapped into
objects and arrays according to _OGC API - Processes_ https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/core/openapi/schemas/result.yaml[results schema] (if `"response"` was set to `"document"`).

[[example_oaproc_result]]
.A route
=================
[source,JSON]
----
{
   "route":
   {
      "value": "(the route object in { } according to the Route Exchange Model)"
   }
}
----

If using `"raw"` rather than `"document"` for the `"response"` in the execution request, the Route Exchange Model GeoJSON would be returned directly.
If using `"reference"` rather than `"value"` for the `"transmissionMode"` in the execution request, then the response will contain an `"href"` linking
to a Route Exchange Model document rather than an inline `"value"`.

If `"mode"` is `"sync"`, the Route Exchange Model is returned directly.

=================
