[appendix]
:appendix-caption: Annex
== Abstract Test Suite (Normative)

This test suite uses the https://en.wikipedia.org/wiki/Given-When-Then[Given-When-Then] notation to specify the tests.

Given input to all tests is a Routing API with its landing page at `{apiURI}` and optional authentication credentials.

=== Conformance Class "Core"

[[conf_core]]
[cols="1,4a",width="90%"]
|===
2+|*Conformance Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/core
|Target type |Web API
|Requirements class |<<rc_core,Requirements Class "Core">>
|Dependency |link:https://docs.ogc.org/DRAFTS/19-072.html#_conformance_class_json[OGC API - Common - Part 1: Core, Conformance Class "JSON"]
|Indirect dependency |link:https://docs.ogc.org/DRAFTS/21-001.html#_conformance_class_route_exchange_model[OGC Route Exchange Model, Conformance Class "Route Exchange Model"]
|===

NOTE: The Conformance Class "JSON" in Common Core has a dependency to the Conformance Classes "Core" and "Landing Page"; that is, testing against "JSON" will automatically test against the dependencies.

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/core/landing-page-link
|Requirements: | <<req_core_landing-page-link,/req/core/landing-page-link>> A
|Test purpose: | Check that the link to the Routes resource exists
|Test method: | 
Given:

* n/a

When:

* the request for the API landing page is executed
** method: `GET`
** path: `{apiURI}`
** header: `Accept: application/json`
** authentication, if authentication credentials are provided

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/json");
* assert that a non-negative integer `n` exists where `/links/n/rel` is "http://www.opengis.net/def/rel/ogc/1.0/routes" and where `/links/n/href` is (after normalization) the URI `{apiURI}/routes`.
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/core/preferences
|Requirements: | <<req_core_conformance-values,/req/core/conformance-values>> A
|Test purpose: | Check that the preference values are stated in the conformance declaration
|Test method: | 
Given:

* n/a

When:

* the request for the API conformance declaration is executed
** method: `GET`
** path: `{apiURI}/conformance`
** header: `Accept: application/json`
** authentication, if authentication credentials are provided

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/json");
* assert that `pass:[/properties/http:~1~1www.opengis.net~1spec~1ogcapi-routes-1~11.0.0-draft.1~1conf~1core/preferences]` is a string array with at least one element.
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/core/compute-route-success
|Requirements: | <<req_core_compute-route-op,/req/core/compute-route-op>> A/B, <<req_core_compute-route-success,/req/core/compute-route-success>> A/B
|Test purpose: | Check that routes can be computed
|Test method: | 
Given:

* a list of five positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` to `{pos5}`)
* a tolerance value

When:

* a request for a route computation is executed for each ordered pair `{posi}`/`{posj}` from { `{pos1}`, `{pos2}`, `{pos3}`, `{pos4}`, `{pos5}` }
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {posi}, {posj} ] } } } }`

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/geo+json");
* assert that the response content conforms to conformance class "Route Exchange Model";
* assert that the distance between the start of the route and `{posi}` is less than the tolerance value;
* assert that the distance between the end of the route and `{posj}` is less than the tolerance value.
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/core/compute-route-error-400
|Requirements: | <<req_core_compute-route-op,/req/core/compute-route-op>> A/B, <<req_core_compute-route-error,/req/core/compute-route-error>> A
|Test purpose: | Check that invalid requests return a 400
|Test method: | 
Given:

* n/a

When:

* a request for a route computation is executed
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "foo": "bar" }`

Then:

* assert a bad request response (status code is "400").
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/core/compute-route-error-422
|Requirements: | <<req_core_compute-route-op,/req/core/compute-route-op>> A/B, <<req_core_compute-route-error,/req/core/compute-route-error>> B
|Test purpose: | Check that invalid requests return a 422
|Test method: | 
Given:

* a list of two positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` and `{pos2}`)
* a list of two positions (each a JSON array with longitude/latitude) that cannot be used as waypoints (`{posA}` and `{posB}`)

When:

* a request for a route computation is executed for each ordered pair `{posi}`/`{posj}` where one position is from { `{pos1}`, `{pos2}` } and the other position is from { `{posA}`, `{posB}` }
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {posi}, {posj} ] } } } }`

Then:

* assert an unprocessable entity response (status code is "422").
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/core/compute-route-preference-success
|Requirements: | <<req_core_compute-route-op,/req/core/compute-route-op>> A/B, <<req_core_compute-route-success,/req/core/compute-route-success>> A/B, <<req_core_conformance-values,/req/core/conformance-values>> A
|Test purpose: | Check that routes can be computed for all preference values
|Test method: | 
Given:

* test /conf/core/preferences has been passed
* a list of five positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` to `{pos5}`)
* a tolerance value

When:

* a request for a route computation is executed for each ordered pair `{posi}`/`{posj}` from { `{pos1}`, `{pos2}`, `{pos3}`, `{pos4}`, `{pos5}` } and for each value `{pref}` from the string array `pass:[/properties/http:~1~1www.opengis.net~1spec~1ogcapi-routes-1~11.0.0-draft.1~1conf~1core/preferences]` in the Conformance Declaration
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "name": "foo bar", "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {posi}, {posj} ] } }, "preference": {pref} } }`

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/geo+json");
* assert that the response content conforms to conformance class "Route Exchange Model";
* assert that the value of `/name` in the response content is "foo bar";
* assert that the distance between the start of the route and `{posi}` is less than the tolerance value;
* assert that the distance between the end of the route and `{posj}` is less than the tolerance value.
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/core/compute-route-preference-error-400
|Requirements: | <<req_core_compute-route-op,/req/core/compute-route-op>> A/B, <<req_core_compute-route-error,/req/core/compute-route-error>> A
|Test purpose: | Check that invalid preference values return a 400
|Test method: | 
Given:

* a list of two positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` and `{pos2}`)

When:

* a request for a route computation is executed
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {pos1}, {pos2} ] } }, "preference": "foo___bar" } }`

Then:

* assert a bad request response (status code is "400").
|===

=== Conformance Class "Intermediate waypoints"

[[conf_intermediate-waypoints]]
[cols="1,4",width="90%"]
|===
2+|*Conformance Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/intermediate-waypoints
|Target type |Web API
|Requirements class |<<rc_intermediate-waypoints,Requirements Class "Intermediate waypoints">>
|Dependency |<<conf_core,Conformance Class "Core">>
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/intermediate-waypoints/compute-route-success
|Requirements: | <<req_intermediate-waypoints_input,/req/intermediate-waypoints/input>> A, <<req_intermediate-waypoints_success,/req/intermediate-waypoints/success>> A
|Test purpose: | Check that routes with intermediate waypoints can be computed
|Test method: | 
Given:

* a list of five positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` to `{pos5}`)
* a tolerance value

When:

* a request for a route computation is executed for each ordered tuple `{posi}`/`{posj}`/`{posk}`/`{posl}`/`{posm}` from { `{pos1}`, `{pos2}`, `{pos3}`, `{pos4}`, `{pos5}` }
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {posi}, {posj}, {posk}, {posl}, {posm} ] } } } }`

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/geo+json");
* assert that the response content conforms to conformance class "Route Exchange Model";
* assert that the distance between the start of the route and `{posi}` is less than the tolerance value;
* assert that the distance between the route path and `{posj}` is less than the tolerance value,
* assert that the distance between the route path and `{posk}` is less than the tolerance value,
* assert that the distance between the route path and `{posl}` is less than the tolerance value,
* assert that the distance between the end of the route and `{posm}` is less than the tolerance value.
|===

=== Conformance Class "Modes"

[[conf_mode]]
[cols="1,4",width="90%"]
|===
2+|*Conformance Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/mode
|Target type |Web API
|Requirements class |<<rc_mode,Requirements Class "Modes">>
|Dependency |<<conf_core,Conformance Class "Core">>
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/mode/modes
|Requirements: | <<req_mode_conformance-values,/req/mode/conformance-values>> A
|Test purpose: | Check that the mode values are stated in the conformance declaration
|Test method: | 
Given:

* n/a

When:

* the request for the API conformance declaration is executed
** method: `GET`
** path: `{apiURI}/conformance`
** header: `Accept: application/json`
** authentication, if authentication credentials are provided

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/json");
* assert that `pass:[/properties/http:~1~1www.opengis.net~1spec~1ogcapi-routes-1~11.0.0-draft.1~1conf~1mode/modes]` is a string array with at least one element.
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/core/compute-route-mode
|Requirements: | <<req_mode_input,/req/mode/input>> A, <<req_mode_conformance-values,/req/mode/conformance-values>> A
|Test purpose: | Check that routes can be computed for all modes
|Test method: | 
Given:

* test /conf/mode/modes has been passed
* a list of five positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` to `{pos5}`)
* a tolerance value

When:

* a request for a route computation is executed for each ordered pair `{posi}`/`{posj}` from { `{pos1}`, `{pos2}`, `{pos3}`, `{pos4}`, `{pos5}` } and for each value `{mode}` from the string array `pass:[/properties/http:~1~1www.opengis.net~1spec~1ogcapi-routes-1~11.0.0-draft.1~1conf~1mode/modes]` in the Conformance Declaration
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {posi}, {posj} ] } }, "mode": {mode} } }`

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/geo+json");
* assert that the response content conforms to conformance class "Route Exchange Model";
* assert that the distance between the start of the route and `{posi}` is less than the tolerance value;
* assert that the distance between the end of the route and `{posj}` is less than the tolerance value.
|===

=== Conformance Class "Height restrictions"

[[conf_height]]
[cols="1,4",width="90%"]
|===
2+|*Conformance Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/height
|Target type |Web API
|Requirements class |<<rc_height,Requirements Class "Height restrictions">>
|Dependency |<<conf_core,Conformance Class "Core">>
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/height/compute-route-success
|Requirements: | <<req_height_input,/req/height/input>> A, <<req_height_success,/req/height/success>> A
|Test purpose: | Check that routes with height restrictions can be computed
|Test method: | 
Given:

* a list of three positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` to `{pos3}`)
* an optional list of vehicle heights, default is: 2, 3, 5
* a tolerance value

When:

* a request for a route computation is executed for each ordered pair `{posi}`/`{posj}` from { `{pos1}`, `{pos2}`, `{pos3}` } and for each `{height}` from the list of vehicle heights
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {posi}, {posj} ] } } }, "height": {height} }`

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/geo+json");
* assert that the response content conforms to conformance class "Route Exchange Model";
* assert that the distance between the start of the route and `{posi}` is less than the tolerance value;
* assert that the distance between the end of the route and `{posj}` is less than the tolerance value;
* assert that the route overview has no property `maxHeight_m` or a value that is greater than or equal to `{height}`.
|===

=== Conformance Class "Weight restrictions"

[[conf_weight]]
[cols="1,4",width="90%"]
|===
2+|*Conformance Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/weight
|Target type |Web API
|Requirements class |<<rc_weight,Requirements Class "Weight restrictions">>
|Dependency |<<conf_core,Conformance Class "Core">>
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/weight/compute-route-success
|Requirements: | <<req_weight_input,/req/weight/input>> A, <<req_weight_success,/req/weight/success>> A
|Test purpose: | Check that routes with weight restrictions can be computed
|Test method: | 
Given:

* a list of three positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` to `{pos3}`)
* an optional list of vehicle weights in metric tons, default is: 3, 5, 10
* a tolerance value

When:

* a request for a route computation is executed for each ordered pair `{posi}`/`{posj}` from { `{pos1}`, `{pos2}`, `{pos3}` } and for each `{weight}` from the list of vehicle weights
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {posi}, {posj} ] } } }, "weight": {weight} }`

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/geo+json");
* assert that the response content conforms to conformance class "Route Exchange Model";
* assert that the distance between the start of the route and `{posi}` is less than the tolerance value;
* assert that the distance between the end of the route and `{posj}` is less than the tolerance value;
* assert that the route overview has no property `maxWeight_t` or a value that is greater than or equal to `{weight}`.
|===

=== Conformance Class "Obstacles"

[[conf_obstacles]]
[cols="1,4",width="90%"]
|===
2+|*Conformance Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/obstacles
|Target type |Web API
|Requirements class |<<rc_obstacles,Requirements Class "Obstacles">>
|Dependency |<<conf_core,Conformance Class "Core">>
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/obstacles/compute-route-success
|Requirements: | <<req_obstacles_input,/req/obstacles/input>> A, <<req_obstacles_success,/req/obstacles/success>> A
|Test purpose: | Check that routes can be computed avoiding obstacles
|Test method: | 
Given:

* a list of five positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` to `{pos5}`)
* a tolerance value

When:

* a request for a route computation is executed for each ordered pair `{posi}`/`{posj}` from { `{pos1}`, `{pos2}`, `{pos3}` }
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {posi}, {posj} ] } } }, "obstacles": { "type": "MultiPolygon", "coordinates": [[[ [{lonm},{latm}], [{lonn},{latm}], [{lonn},{latn}], {[{lonm},{latn}], [{lonm},{latm}] ]]] } }` with
*** `{lonm}` and `{lonn}` as longitudes somewhere between the longitudes of `{posi}` and `{posj}`; `{lonm}` < `{lonn}`
*** `{latm}` and `{latn}` as latitudes somewhere between the latitudes of `{posi}` and `{posj}`; `{latm}` < `{latn}`

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/geo+json");
* assert that the response content conforms to conformance class "Route Exchange Model";
* assert that the distance between the start of the route and `{posi}` is less than the tolerance value;
* assert that the distance between the end of the route and `{posj}` is less than the tolerance value;
* assert that the route path does not intersect the obstacle geometry.
|===

=== Conformance Class "Temporal constraints"

[[conf_time]]
[cols="1,4",width="90%"]
|===
2+|*Conformance Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/time
|Target type |Web API
|Requirements class |<<rc_time,Requirements Class "Temporal constraints">>
|Dependency |<<conf_core,Conformance Class "Core">>
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/time/compute-route-success-default
|Requirements: | <<req_time_input,/req/time/input>> A/B, <<req_time_success,/req/time/success>> A/B/C
|Test purpose: | Check that routes with the default time constraints can be computed
|Test method: | 
Given:

* a list of three positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` to `{pos3}`)
* a tolerance value

When:

* a request for a route computation is executed for each ordered pair `{posi}`/`{posj}` from { `{pos1}`, `{pos2}`, `{pos3}` }
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {posi}, {posj} ] } } } }`

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/geo+json");
* assert that the response content conforms to conformance class "Route Exchange Model";
* assert that the distance between the start of the route and `{posi}` is less than the tolerance value;
* assert that the distance between the end of the route and `{posj}` is less than the tolerance value;
* assert that the start feature has a `timestamp` property that is the same as the time when the request was submitted - within the specified tolerance;
* assert that the difference between the end and start feature `timestamp` properties is the same as the `duration_s` property of the route overview - within the specified tolerance;
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/time/compute-route-success
|Requirements: | <<req_time_input,/req/time/input>> A/B, <<req_time_success,/req/time/success>> A/B/C
|Test purpose: | Check that routes with time constraints can be computed
|Test method: | 
Given:

* a list of three positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` to `{pos3}`)
* a tolerance value

When:

* a request for a route computation is executed for each ordered pair `{posi}`/`{posj}` from { `{pos1}`, `{pos2}`, `{pos3}` } and for `{type}` from the list: "departure", "arrival".
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {posi}, {posj} ] } } }, "when": { "value": { "timestamp": {timestamp}, "type": {type} } } }` with
*** `{timestamp}` as a RFC 3339 date-time value in UTC ("Z") in 24 hours

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/geo+json");
* assert that the response content conforms to conformance class "Route Exchange Model";
* assert that the distance between the start of the route and `{posi}` is less than the tolerance value;
* assert that the distance between the end of the route and `{posj}` is less than the tolerance value;
* assert that, if `{type}` is "departure", the start feature has a `timestamp` property that is the same as `{timestamp}` - within the specified tolerance;
* assert that, if `{type}` is "arrival", the end feature has a `timestamp` property that is the same as `{timestamp}` - within the specified tolerance;
* assert that the difference between the end and start feature `timestamp` properties that is the same as the `duration_s` property of the route overview - within the specified tolerance;
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/time/compute-route-success-400-error
|Requirements: | <<req_time_input,/req/time/input>> A/B
|Test purpose: | Check that routes with invalid time constraints are rejected
|Test method: | 
Given:

* a list of two positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` and `{pos2}`)
* a tolerance value

When:

* requests for a route computation are executed with `{timestamp}` as an invalid value: without time zone, with a timezone that is not "Z", and a date.
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {pos1}, {pos2} ] } } }, "when": { "value": { "timestamp": {timestamp} } } }`

Then:

* assert a bad request response (status code is "400").
|===

=== Conformance Class "Manage routes"

[[conf_manage-routes]]
[cols="1,4",width="90%"]
|===
2+|*Conformance Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/manage-routes
|Target type |Web API
|Requirements class |<<rc_manage-routes,Requirements Class "Manage routes">>
|Dependency |<<conf_core,Conformance Class "Core">>
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/manage-routes/routes-success-1
|Requirements: | <<req_manage-routes_routes-success,/req/manage-routes/routes-success>> A
|Test purpose: | Check that a link to the stored route is returned (part 1)
|Test method: | 
Given:

* a list of two positions (each a JSON array with longitude/latitude) that can be used as waypoints (`{pos1}` and `{pos2}`)

When:

* a request for a route computation is executed
** method: `POST`
** path: `{apiURI}/routes`
** header: `Content-Type: application/json`, `Accept: application/geo+json`
** authentication, if authentication credentials are provided
** content: `{ "name": "foo bar", "inputs": { "waypoints": { "value": { "type": "MultiPoint", "coordinates": [ {pos1}, {pos2} ] } } } }`

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/geo+json");
* assert that response includes a header `Location`;
* assert the the `Location` header refers to URI that matches the template `{apiURI}/routes/{routeId}`.
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/manage-routes/routes-success-2
|Requirements: | <<req_manage-routes_routes-success,/req/manage-routes/routes-success>> A
|Test purpose: | Check that a link to the stored route is returned (part 2)
|Test method: | 
Given:

* test /conf/manage-routes/routes-success-1 has just been passed
* `{routeId}` is the route identifier of a stored route based on the `Location` header value from the test /conf/manage-routes/routes-success-1
* `{routeContent}` is the content of the response from the test /conf/manage-routes/routes-success-1

When:

* a request to fetch the stored route is executed
** method: `GET`
** path: `{apiURI}/routes/{routeId}`
** header: `Accept: application/geo+json`
** authentication, if authentication credentials are provided

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/geo+json");
* assert that the response content conforms to conformance class "Route Exchange Model";
* assert that response content is identical to `{routeContent}`.
|===


==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/manage-routes/get-routes-success
|Requirements: | <<req_manage-routes_get-routes-op,/req/manage-routes/get-routes-op>> A, <<req_manage-routes_get-routes-success,/req/manage-routes/get-routes-success>> A/B/C/D
|Test purpose: | Check that routes can be fetched
|Test method: | 
Given:

* test /conf/manage-routes/routes-success-1 has just been passed
* `{routeId}` is the route identifier of a stored route based on the `Location` header value from the test /conf/manage-routes/routes-success-1

When:

* a request to fetch the list of routes is executed
** method: `GET`
** path: `{apiURI}/routes`
** header: `Accept: application/json`
** authentication, if authentication credentials are provided

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/json");
* assert that the response content validates against the schema in <<req_manage-routes_get-routes-success,/req/manage-routes/get-routes-success>> B;
* assert that a non-negative integer `n` exists where `/links/n/rel` is "item", where `/links/n/href` is (after URI normalization) equal to `{apiURI}/routes/{routeId}` and where `links/n/title` includes the sub-string "foo bar".
|===


==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/manage-routes/get-route-success
|Requirements: | <<req_manage-routes_get-route-op,/req/manage-routes/get-route-op>> A, <<req_manage-routes_get-route-success,/req/manage-routes/get-route-success>> A
|Test purpose: | Check that routes can be fetched
|Test method: | 
Given:

* test /conf/manage-routes/get-routes-success has just been passed
* `{routeIds}` is an array of route identifiers from the test /conf/manage-routes/get-routes-success (derived from the `/links/i/href` values for all non-integer i where `/links/i/rel` is "item")

When:

* requests to fetch a route are executed with each `{routeId}` from `{routeIds}`
** method: `GET`
** path: `{apiURI}/routes/{routeId}`
** header: `Accept: application/geo+json`
** authentication, if authentication credentials are provided

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/geo+json");
* assert that the response content conforms to conformance class "Route Exchange Model".
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/manage-routes/get-route-definition-success
|Requirements: | <<req_manage-routes_get-route-definition-op,/req/manage-routes/get-route-definition-op>> A, <<req_manage-routes_get-route-definition-success,/req/manage-routes/get-route-definition-success>> A/B
|Test purpose: | Check that route definitions can be fetched
|Test method: | 
Given:

* tests /conf/manage-routes/routes-success-1 and /conf/manage-routes/get-routes-success have just been passed
* `{routeIds}` is an array of route identifiers from the test /conf/manage-routes/get-routes-success (derived from the `/links/i/href` values for all non-integer i where `/links/i/rel` is "item")
* `{routeIdCreated}` is the route identifier of a stored route based on the `Location` header value from the test /conf/manage-routes/routes-success-1
* `{routeDefinitionCreated}` is the request content of the test /conf/manage-routes/routes-success-1

When:

* requests to fetch a route are executed with each `{routeId}` from `{routeIds}`
** method: `GET`
** path: `{apiURI}/routes/{routeId}/definition`
** header: `Accept: application/json`
** authentication, if authentication credentials are provided

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/json");
* if `{routeId}` is equal to `{routeIdCreated}`, assert that the response content is identical to `{routeDefinitionCreated}`;
* assert that the response content validates against the following OpenAPI 3.0 schema:

[source,YAML]
----
type: object
required:
  - inputs
properties:
  inputs:
    type: object
    required:
      - waypoints
    properties:
      name:
        type: string
      waypoints:
        type: object
        required:
          - value
        properties:
          value:
            type: object
            required:
              - type
              - coordinates
            properties:
              type:
                type: string
                enum:
                  - MultiPoint
              coordinates:
                type: array
                minItems: 2
                items:
                  title: Points along the route
                  type: array
                  minItems: 2
                  maxItems: 3
                  items:
                    type: number
      preference:
        type: string
      mode:
        type: string
      height:
        type: number
        minimum: 0
      weight:
        type: number
        minimum: 0
      obstacles:  
        type: object
        required:
          - value
        properties:
          value:
            type: object
            required:
              - type
              - coordinates
            properties:
              type:
                type: string
                enum:
                  - MultiPolygon
              coordinates:
                type: array
                items:
                  type: array
                  items:
                    type: array
                    minItems: 4
                    items:
                      type: array
                      minItems: 2
                      maxItems: 3
                      items:
                        type: number
      when:
        type: object
        required:
          - value
        properties:
          value:
            type: object
            required:
              - timestamp
            properties:
              timestamp:
                type: string
                format: date-time
              type:
                type: string
                default: departure
                enum:
                  - departure
                  - arrival
----
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/manage-routes/delete-route-success-1
|Requirements: | <<req_manage-routes_delete-route-op,/req/manage-routes/delete-route-op>> A, <<req_manage-routes_delete-route-success,/req/manage-routes/delete-route-success>> A/B
|Test purpose: | Check that a route can be deleted
|Test method: | 
Given:

* test /conf/manage-routes/routes-success-1 has just been passed
* `{routeId}` is the route identifier of a stored route based on the `Location` header value from the test /conf/manage-routes/routes-success-1

When:

* a request to delete a route
** method: `DELETE`
** path: `{apiURI}/routes/{routeId}`
** authentication, if authentication credentials are provided

Then:

* assert response (status code is "200", "204" or "202").
|===

==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/manage-routes/delete-route-success-2
|Requirements: | <<req_manage-routes_delete-route-success,/req/manage-routes/delete-route-success>> A
|Test purpose: | Check that a route has been deleted
|Test method: | 
Given:

* test /conf/manage-routes/delete-route-success-1 has just been passed
* `{routeId}` is the route identifier of the deleted route in test /conf/manage-routes/delete-route-success-1

When:

* a request to fetch all routes
** method: `GET`
** path: `{apiURI}/routes`
** header: `Accept: application/json`
** authentication, if authentication credentials are provided

Then:

* assert successful execution (status code is "200", `Content-Type` header is "application/json");
* assert that no non-negative integer `n` exists where `/links/n/rel` is "item", where `/links/n/href` is (after URI normalization) equal to `{apiURI}/routes/{routeId}`.
|===
