== Conformance

This Standard defines the following requirements and conformance classes:

* Minimal routing capability:
** **Core**: Routing based on start/end point
* Additional API capabilities:
** **Manage route**: Store, fetch and delete routes stored on the server
* Additional routing parameters:
** **Mode**: Specify the type of transport desired when computing the route
** **Intermediate waypoints**: Pass through additional points along the route
** **Height restrictions**: Consider a specified vehicle height in meters against known height restrictions when computing the route
** **Weight restrictions**: Consider a specified vehicle weight in metric tons (tonnes) against known weight restrictions when computing the route
** **Obstacles**: Avoid obstacles
** **Temporal constraints**: Specify departure/arrival time

Requirements for a single standardization target types are considered: Web API.

Conformance with this Standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC® Standard, a software implementation shall choose to implement:

* Any one of the conformance classes specified in Annex A (normative).

All requirements-classes and conformance-classes described in this document are owned by the Standard(s) identified.
