[[routing-api]]
== Routing API

=== Overview

This clause specifies the Routing API as a Web API for routing based on the OGC API principles and OGC API - Common as well as the Route Exchange Model. It consists of the following requirements/conformance classes:

* Minimal routing capability:
** **Core**: Routing based on start/end point
* Additional API capabilities:
** **Manage routes**: Store, fetch and delete routes stored on the server
* Additional routing parameters:
** **Mode**: Specify the type of transport when computing the route
** **Intermediate waypoints**: Pass through additional points along the route
** **Height restrictions**: Consider a specified vehicle height in meters against known height restrictions when computing the route
** **Weight restrictions**: Consider a specified vehicle weight in metric tons (tonnes) against known weight restrictions when computing the route
** **Obstacles**: Avoid obstacles
** **Temporal constraints**: Specify departure/arrival time

The API building blocks support the resources and operations listed in Table 1.

[#tldr,reftext='{table-caption} {counter:table-num}']
.Overview of resources and applicable HTTP methods and media types
[cols="16,20,10,18,18,18",options="header"]
!===
|Resource |Path |HTTP method |Request media type |Response media type |Document reference
|Landing page |`/` |GET |n/a |`application/json` |<<landing_page>>
|Conformance declaration |`/conformance` |GET |n/a |`application/json` |<<conformance_declaration>>
.2+|Routes .2+|`/routes` |POST |`application/json` |`application/geo+json` |<<compute_route>>
|GET |n/a |`application/json` |<<get_routes>>
.2+|Route .2+|`/routes/{routeId}` |GET |n/a |`application/geo+json` |<<get_route>>
|DELETE |n/a |n/a |<<delete_route>>
|Route definition |`/routes/{routeId} /definition` |GET |n/a |`application/json` |<<get_route_definition>>
!===

The first three operations are available in the 'Core' requirements class, i.e. all routing
APIs will support them. The other four operations are implemented by routing APIs implementing the
'Manage routes' requirements class.

[[rc_core]]
=== Requirements Class "Core"

[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/req/core
|Target type |Web API
|Dependency |<<CommonCore,OGC API - Common - Part 1: Core, Requirements Classes "Core", "Landing Page", "JSON">>
|Dependency |<<GeoJSON,GeoJSON>>
|Dependency |<<REM,OGC Route Exchange Model, Requirements Class "Route Exchange Model">>
|Dependency |<<rfc8288,Web Linking>>
|===

==== OGC API - Common - Part 1: Core

At the time of writing, <<CommonCore,OGC API - Common - Part 1: Core>> is a candidate standard and not yet published. The requirements classes "Core", "Landing Page" and "JSON" have to be supported. This includes support for the resources Landing Page, Conformance Declaration and API Definition. Support for the "HTML" and "OpenAPI 3.0" requirements classes is recommended.

[[landing_page]]
==== API landing page

[[req_core_root-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/compute-route-op*
^|A |The content of the response SHALL include a link to the Routes resource at path `/routes` (link relation type `\http://www.opengis.net/def/rel/ogc/1.0/routes``).
|===

The following is an example of the landing page of a routing API.

[[example_lp]]
.Landing page
=================
[source,JSON]
----
{
  "links": [
    {
      "href": "https://example.org/api/routing/v1",
      "rel": "self",
      "type": "application/json",
      "title": "This document"
    },
    {
      "href": "https://example.org/api/routing/v1/api",
      "rel": "service-desc",
      "type": "application/vnd.oai.openapi+json;version=3.0",
      "title": "The API definition in OpenAPI JSON"
    },
    {
      "href": "https://example.org/api/routing/v1/api.html",
      "rel": "service-doc",
      "type": "text/html",
      "title": "The API documentation in HTML"
    },
    {
      "href": "https://example.org/api/routing/v1/conformance",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/conformance",
      "type": "application/json",
      "title": "The list of conformance classes implemented by this API"
    },
    {
      "href": "https://example.org/api/routing/v1/routes",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/routes",
      "type": "application/json",
      "title": "Compute routes"
    }
  ]
}
----
=================

[[conformance_declaration]]
==== Declaration of conformance classes

The following is an example of the conformance declaration of a routing API that implements all requirements classes.

Requirements classes can support options and parsing the API definition may be unnecessarily costly for clients to determine the options. The conformance declaration, therefore, is extended to support stating the options of a conformance class in a `properties` member where the conformance class URI is the key for the options of that conformance class.

[[example_cc]]
.Conformance declaration
=================
[source,JSON]
----
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/core",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/mode",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/intermediate-waypoints",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/height",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/weight",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/obstacles",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/time",
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/manage-routes"
  ],
  "properties": {
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/core": {
      "preferences": [
        "fastest",
        "shortest"
      ]
    },
    "http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/mode": {
      "modes": [
        "motor-vehicle",
        "bicycle",
        "pedestrian"
      ]
    }
  }
}
----
=================

[[geometries]]
==== Geometries

All geometries used in the API are GeoJSON geometries. This includes the waypoints in the route definition and the geometries of all features in the route exchange model (overview, start, end, segments).

All geometries use coordinates based on the World Geodetic System 1984 (WGS 84) datum, i.e., the coordinate reference system used by Global Positioning System (GPS). In GeoJSON, a coordinate is an array of numbers. The first two elements are longitude and latitude, or easting and northing, precisely in that order and using decimal numbers. Height may be included as an optional third element.

Support for additional encodings or additional coordinate reference systems can be specified in future extensions.

[[routes]]
==== Routes

[[compute_route]]
===== Compute a new route

This operation creates a new route. The payload of the request specifies the definition of the new route.

The core requirements class supports a minimum route definition by two `waypoints`, the start and end point of the route.

In addition, clients can select a cost function as the routing `preference`. The API declares the cost functions that it supports in the Conformance Declaration resource and in the API definition.

An optional `name` for the route can be provided. The name can be used as the title in links to the route and is also included in the route itself.

[[req_core_compute-route-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/compute-route-op*
^|A |The server SHALL support the HTTP POST operation at the path `/routes`.
^|B |The server SHALL accept a route definition in the content of the request based upon the following OpenAPI 3.0 schema:

[source,YAML]
----
type: object
required:
  - inputs
properties:
  inputs:
    type: object
    required:
      - waypoints
    properties:
      name:
        type: string
      waypoints:
        type: object
        required:
          - value
        properties:
          value:
            type: object
            required:
              - type
              - coordinates
            properties:
              type:
                type: string
                enum:
                  - MultiPoint
              coordinates:
                type: array
                minItems: 2
                maxItems: 2
                items:
                  title: Points along the route
                  type: array
                  minItems: 2
                  items:
                    type: number
      preference:
        type: string
----
^|C |The schema of the `preference` member SHALL be extended with `enum` and `default` values to declare the cost functions supported by the server.
|===

Additional members in the route definition can be ignored.

NOTE: The content model of the route definition object has been designed so that it can be a valid request to an process execution request according to OGC API - Processes. This adds additional members "inputs" and "value" that would otherwise be unnecessary.

[[req_core_conformance-values]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/conformance-values*
^|A |The content of the conformance declaration response at path `/conformance` SHALL list all values that the `preference` parameter supports, based upon the following OpenAPI 3.0 schema:

[source,YAML]
----
type: object
required:
  - properties
properties:
  properties:
    type: object
    required:
      - http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/core
    properties:
      http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/core:
        type: object
        required:
          - preferences
        properties:
          preferences:
            type: array
            items:
              minItems: 1
              type: string
----
^|B |The first value listed in the array SHALL be the default cost function, if no preference is specified in the route definition.
|===

See <<example_cc>> for an example.

NOTE: It is planned to register well-known cost functions with the OGC Naming Authority that are recommended for use, where applicable. Once a register has been established, this specification will be updated. Until then, use `fastest` for cost functions that optimize duration and `shortest` for cost functions that optimize distance.

The preference is a client hint and it is the decision of the server how to consider the preference in the computation of the route.

[[req_core_compute-route-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/compute-route-success*
^|A |A successful, synchronous execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|B |By default (and this requirements class provides no mechanism to change the default), the content SHALL conform to the requirements class "Route Exchange Model".
^|C |Height SHALL be provided for all coordinates in the route or for no coordinates in the route.
|===

[[rec_core_compute-route-success]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/compute-route-success*
^|A |If the request included an `Accept-Language` header, the server SHOULD try to honor the request and otherwise fall back to an available language.
^|B |The response SHOULD include a `Content-Language` header with the language used for instructions and names, in particular road/street names, if the language of the text values is known and the same language is used for all text fields in the route.
|===

This requirements class only specifies requirements for the synchronous execution of a routing request. Requirements for the asynchronous execution can be added in a future extension.

[[req_core_error]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/error*
^|A |If the request does not conform to the requirements (e.g., the route definition is invalid) a response with status code `400` SHALL be returned.
^|B |If the request is valid, but the server is not able to process the request (e.g., the server has insufficient route network data for the request), a response with status code `422` SHALL be returned.
|===

[[example_route_definition]]
.Route definition
=================
This requests the fastest route from Reagan Airport to the U.S. Capitol
in Washington, D.C.

[source,JSON]
----
{
  "inputs": {
    "name": "Reagan Airport to Capitol",
    "waypoints": {
      "value": {
        "type": "MultiPoint",
        "coordinates": [
          [
            -77.037722,
            38.851444
          ],
          [
            -77.009003,
            38.889931
          ]
        ]
      }
    },
    "preference": "fastest"
  }
}
----
=================

[[example_route]]
.A route
=================
[source,JSON]
----
{
  "type": "FeatureCollection",
  "name": "Reagan Airport to Capitol",
  "features": [
    {
      "type": "Feature",
      "id": 1,
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -77.037722,
            38.851444
          ],
          ...,
          [
            -77.012520,
            38.889780
          ]
        ]
      },
      "properties": {
        "featureType": "route overview",
        "length_m": 8213,
        "duration_s": 483
      }
    },
    {
      "type": "Feature",
      "id": 2,
      "geometry": {
        "type": "Point",
        "coordinates": [
          -77.037722,
          38.851444
        ]
      },
      "properties": {
        "featureType": "start"
      }
    },
    {
      "type": "Feature",
      "id": 3,
      "geometry": {
        "type": "Point",
        "coordinates": [
          -77.041674,
          38.871088
        ]
      },
      "properties": {
        "featureType": "segment",
        "length_m": 3314,
        "duration_s": 213,
        "instruction": "turn right",
        "roadName": "George Washington Memorial Pkwy",
        "maxHeight": 4.5,
        "speedLimit": 55,
        "speedLimitUnit": "mph"
      }
    },
    ...,
    {
      "type": "Feature",
      "id": 17,
      "geometry": {
        "type": "Point",
        "coordinates": [
          -77.012520,
          38.889780
        ]
      },
      "properties": {
        "featureType": "segment",
        "length_m": 517,
        "duration_s": 73,
        "roadName": "First Street",
        "speedLimit": 35,
        "speedLimitUnit": "mph"
      }
    },
    {
      "type": "Feature",
      "id": 18,
      "geometry": {
        "type": "Point",
        "coordinates": [
          -77.012520,
          38.889780
        ]
      },
      "properties": {
        "featureType": "end"
      }
    }
  ]
}
----
=================

[[rc_manage-routes]]
=== Requirements Class "Manage routes"

[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/req/manage-routes
|Target type |Web API
|Dependency |<<rc_core>>
|===

[[route2]]
==== Routes

[[req_manage-routes_routes-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-routes/routes-success*
^|A |The response to a successful execution of the operation to compute a route SHALL include a header `Location` with the URI of the new route that is a direct sub-resource of `/routes`.
|===

[[example_route_location]]
.New route request
=================
In the response to a synchronous request to compute a route, the server returns the route in the payload, but also the URI of the new route (`https://example.org/api/routing/v1/routes/hdg6g`) on the server.

[source]
----
POST /api/routing/v1/routes HTTP/1.1
Host: example.org
Content-Type: application/json

{ ... the route definition ... }

HTTP/1.1 200 OK
Date: Tue, 22 Dec 2021 16:42:23 GMT
Location: https://example.org/api/routing/v1/routes/hdg6g
Content-Type: application/geo+json

{ ... the route ... }
----
=================

[[per_manage-routes_purge-routes]]
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/manage-routes/purge-routes*
^|A |Routing APIs may purge routes stored on the server automatically.
|===

Typically, routes will be removed after a reasonable time, for example, a few hours after the route has last been accessed.

[[get_routes]]
===== Fetch routes

This operation returns a list of routes that are currently available.

[[req_manage-routes_get-routes-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-routes/get-routes-op*
^|A |The server SHALL support the HTTP GET operation at the path `/routes`.
|===

[[req_manage-routes_get-routes-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-routes/get-routes-success*
^|A |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|B |The content of that response SHALL be based upon the following OpenAPI 3.0 schema:

[source,YAML]
----
type: object
properties:
  links:
    type: array
    items:
      type: object
      required:
        - rel
        - href
      properties:
        href:
          type: string
        rel:
          type: string
        type:
          type: string
        hreflang:
          type: string
        title:
          type: string
----
^|C |The links SHALL include a link (link relation `item`) to a route currently on the server.
^|D |If a route has a name, the name SHALL be used in the link title.
|===

Access to this resource will typically require authentication. The server will only include links 
to routes that the client is authorized to access.

[[example_routes]]
.Routes
=================
[source,JSON]
----
{
  "links": [
    {
      "href": "https://example.org/api/routing/v1/routes",
      "rel": "self",
      "type": "application/json",
      "title": "This document"
    },
    {
      "href": "https://example.org/api/routing/v1/routes/5hsb32",
      "rel": "item",
      "type": "application/geo+json",
      "title": "Lincoln Memorial to hotel"
    },
    {
      "href": "https://example.org/api/routing/v1/routes/9fg3dh",
      "rel": "item",
      "type": "application/geo+json",
      "title": "Lafayette Square to Zoo"
    },
    {
      "href": "https://example.org/api/routing/v1/routes/j6gdg3",
      "rel": "item",
      "type": "application/geo+json",
      "title": "DCA to hotel"
    }
  ]
}
----
=================

[[route]]
==== Route

[[get_route]]
===== Fetch a route

This operation returns the route with id `routeId`. The route content is
described by the "Route Exchange Model".

[[req_manage-routes_get-route-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-routes/get-route-op*
^|A |The server SHALL support the HTTP GET operation at the path `/routes/{routeId}`
for each route referenced from the Routes resource at `/routes`.
|===

[[req_manage-routes_get-route-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-routes/get-route-success*
^|A |The response to the request SHALL conform to the requirement `/req/core/compute-route-success`.
|===

See <<example_route>> for an example of a route.

[[delete_route]]
===== Delete a route

This operation deletes the route with identifier `routeId`.
If the route is still in processing, the routing process is canceled.

[[req_manage-routes_delete-route-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-routes/delete-route-op*
^|A |The server SHALL support the HTTP DELETE operation at the path `/routes/{routeId}` for each route referenced from the Routes resource at `/routes`.
|===

[[req_manage-routes_delete-route-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-routes/delete-route-success*
^|A |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200` or `204`.
^|B |If the operation is not executed immediately, but is added to a processing queue, the response SHALL have a HTTP status code `202`.
|===

After the execution of the request, the route will no longer be included in the Routes resource (path `/routes`) and a GET request to `/routes/{routeId}` will return a response with a HTTP status code `404`.

[[route_definition]]
==== Route definition

[[get_route_definition]]
===== Fetch the definition of a route

This operation returns the input parameters used to create the route with id `routeId`.

[[req_core_route-definition-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/async/route-definition-op*
^|A |The server SHALL support the HTTP GET operation at the path `/routes/{routeId}/definition` for each route referenced from the Routes resource at `/routes`.
|===

[[req_core_route-definition-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/async/route-definition-success*
^|A |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|B |The content of that response SHALL be identical to the content of the POST request to `/routes` when the route was created.
|===

[[rc_intermediate-waypoints]]
=== Requirements Class "Intermediate waypoints"

Additional waypoints along the route between start and end to consider
when computing the route.

[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/req/intermediate-waypoints
|Target type |Web API
|Dependency |<<rc_core>>
|===

[[req_intermediate-waypoints_input]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/intermediate-waypoints/input*
^|A |The server SHALL support more than two points in the member with the
name "waypoints" in the route definition in a HTTP POST request to the
path `/routes` (i.e. `maxItems` may be removed from the schema definition
or increased to a value larger than '2').
|===

[[req_intermediate-waypoints_success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/intermediate-waypoints/success*
^|A |The computed route SHALL pass through all waypoints in the order
in which they have been provided. "Pass through" means that the route
overview line string geometry passes through the position or a position
on the route network that is close to the waypoint.
|===

[[rc_mode]]
=== Requirements Class "Modes"

Mode is a restriction based on the type of transport desired when computing the route. For instance, "On Road", "Off Road". The API declares the modes that it supports.

[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/req/mode
|Target type |Web API
|Dependency |<<rc_core>>
|===

[[req_mode_input]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/mode/input*
^|A |The server SHALL support a member with the name "mode"
in the route definition in a HTTP POST request to the path `/routes`
with the following base schema:

[source,YAML]
----
name: mode
in: query
schema:
  type: string
----
^|B |The schema of the `mode` member SHALL be extended with `enum` and `default` values to declare the mode options supported by the server.
|===

[[req_mode_conformance-values]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/conformance-values*
^|A |The content of the conformance declaration response at path `/conformance` SHALL list all values that the `mode` parameter supports, based upon the following OpenAPI 3.0 schema:

[source,YAML]
----
type: object
required:
  - properties
properties:
  properties:
    type: object
    required:
      - http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/mode
    properties:
      http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/mode:
        type: object
        required:
          - modes
        properties:
          modes:
            type: array
            items:
              minItems: 1
              type: string
----
^|B |The first value listed in the array SHALL be the default mode, if no mode is specified in the route definition.
|===

See <<example_cc>> for an example.

NOTE: It is planned to register well-known modes with the OGC Naming Authority that are recommended for use, where applicable. Once a register has been established, this specification will be updated.

The mode is a client hint and it is the decision of the server how to consider the selected mode in the computation of the route.

[[rc_height]]
=== Requirements Class "Height restrictions"

Consider a specified vehicle height in meters against known height restrictions when computing the route.

[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/req/height
|Target type |Web API
|Dependency |<<rc_core>>
|===

[[req_height_input]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/height/input*
^|A |The server SHALL support a member with the name "height"
in the route definition in a HTTP POST request to the path `/routes`
with the following schema:

[source,YAML]
----
name: height
in: query
schema:
  type: number
----
|===

[[req_height_success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/height/success*
^|A |The computed route SHALL be passable by vehicles with a height up to
the value of "height" in meters.
|===

[[rc_weight]]
=== Requirements Class "Weight restrictions"

Consider a specified vehicle weight in metric tons (tonnes) against known weight restrictions when computing the route.

[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/req/weight
|Target type |Web API
|Dependency |<<rc_core>>
|===

[[req_weight_input]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/weight/input*
^|A |The server SHALL support a member with the name "weight"
in the route definition in a HTTP POST request to the path `/routes`
with the following schema:

[source,YAML]
----
name: weight
in: query
schema:
  type: number
----
|===

[[req_weight_success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/weight/success*
^|A |The computed route SHALL be passable by vehicles with a weight up to the value of "weight" in metric tons (tonnes).
|===

[[rc_obstacles]]
=== Requirements Class "Obstacles"

One or more polygons describing areas the route should avoid.

[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/req/obstacles
|Target type |Web API
|Dependency |<<rc_core>>
|===

[[req_obstacles_input]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/obstacles/input*
^|A |The server SHALL support a member with the name "obstacles"
in the route definition in a HTTP POST request to the path `/routes`
with the following schema (a GeoJSON MultiPolygon, wrapped into a 
"value" member):

[source,YAML]
----
type: object
required:
  - value
properties:
  value:
    type: object
    required:
      - type
      - coordinates
    properties:
      type:
        type: string
        enum:
          - MultiPolygon
      coordinates:
        type: array
        items:
          type: array
          items:
            type: array
            minItems: 4
            items:
              type: array
              minItems: 2
              items:
                type: number
----
|===

[[req_obstacles_success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/obstacles/success*
^|A |The computed route SHALL not pass through the polygons identified as obstacles.
|===

[[rc_time]]
=== Requirements Class "Temporal constraints"

The time of departure or arrival. The default value is an immediate departure.

[cols="1,4",width="90%"]
|===
2+|*Requirements Class*
2+|http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/req/time
|Target type |Web API
|Dependency |<<rc_core>>
|===

[[req_time_input]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/time/input*
^|A |The server SHALL support a member with the name "when"
in the route definition in a HTTP POST request to the path `/routes`
with the following schema:

[source,YAML]
----
type: object
required:
  - value
properties:
  value:
    type: object
    required:
      - timestamp
    properties:
      timestamp:
        type: string
        format: date-time
        example: "2019-05-23T19:06:32Z"
      type:
        type: string
        default: departure
        enum:
          - departure
          - arrival
----
|===

[[req_time_success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/time/success*
^|A |All temporal information in the route SHALL be based on the values in
the "when" member (the time of departure or arrival, the default value is
an immediate departure).
|===

[[rec_time_success]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/time/success*
^|A |The route SHOULD consider the expected traffic situation at the time
specified in the "when" member.
|===
