== Conformance

This Standard defines the following requirements and conformance classes:

* Minimal routing capability:
** **Core**: Routing based on start/end point
* Additional API capabilities:
** **Asynchronous execution**: Return the route in the response to the routing request
** **Callback**: Support for call to a webhook after the route is computed
** **Delete route**: Cancel/delete routes
** **Result set**: Request parts of the Route Exchange Model, e.g., in DDIL situations
* Additional routing parameters:
** **Intermediate waypoints**: Pass through additional points along the route
** **Height restrictions**: Consider a specified vehicle height in meters against known height restrictions when computing the route
** **Load restrictions**: Consider a specified vehicle weight in tons against known weight restrictions when computing the route
** **Obstacles**: Avoid obstacles
** **Temporal constraints**: Specify departure/arrival time

Requirements for a single standardization target types are considered: Web API.

Conformance with this Standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC® Standard, a software implementation shall choose to implement:

* Any one of the conformance classes specified in Annex A (normative).

All requirements-classes and conformance-classes described in this document are owned by the Standard(s) identified.
