== Conventions

=== Identifiers

The normative provisions in this Standard are denoted by the URI

http://www.opengis.net/spec/ogcapi-routes-1/1.0

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Link relations

To express relationships between resources, <<rfc8288,RFC 8288 (Web Linking)>> is used.

The following <<link-relations,registered link relation types [IANA]>> are used in this document:

* **describedby**: Refers to a resource providing information about the link's context.
* **item**: The target IRI points to a resource that is a member of the collection represented by the context IRI.
* **next**: Indicates that the link's context is a part of a series, and that the next in the series is the link target.
* **self**: Conveys an identifier for the link's context.
* **service-desc**: Identifies service description for the context that is primarily intended for consumption by machines.
* **service-doc**: Identifies service documentation for the context that is primarily intended for human consumption.

The following <<link-relations-ogc,link relation types registered by the OGC Naming Authority>> are used in this document:

* **http://www.opengis.net/def/rel/OGC/1.0/conformance**: Refers to a resource that identifies the specifications that the link’s context conforms to.
* **http://www.opengis.net/def/rel/OGC/1.0/routes**: Refers to a Routes resource.
* **http://www.opengis.net/def/rel/OGC/1.0/subscriber**: Refers to a resource that accepts callback requests.

Each resource representation includes an array of links. Implementations are free to add additional links for all resources provided by the API.

=== Use of HTTPS

For simplicity, this document in general only refers to the HTTP protocol. This is not meant to exclude the use of HTTPS and simply is a shorthand notation for "HTTP or HTTPS." In fact, most servers are expected to use HTTPS, not HTTP.

=== References to OpenAPI components in normative statements

This document uses OpenAPI 3.0 fragments as examples and to formally state requirements. However, using OpenAPI 3.0 is not required for implementing a server.

In this document, fragments of OpenAPI definitions are shown in YAML (YAML Ain't Markup Language) since YAML is easier to read than JSON and is typically used in OpenAPI editors. YAML is described by its authors as a human friendly data serialization standard for all programming languages.

Some normative statements (requirements, recommendations and permissions) use a phrase that a component in the API definition of the server must be "based upon" a schema or parameter component in the OGC schema repository.

In the case above, the following changes to the pre-defined OpenAPI component are permitted.

* The range of values of a parameter or property may be extended (additional values) or constrained (if a subset of all possible values are applicable to the server). An example for a constrained range of values is to explicitly specify the supported values of a string parameter or property using an enum.
* The default value of a parameter may be changed or added unless a requirement explicitly prohibits this.
* Additional properties may be added to the schema definition of a Response Object.
* Informative text may be changed or added, like comments or description properties.
* If the server supports an XML encoding, `xml` properties may be added to the relevant OpenAPI schema components.

For API definitions that do not conform to the OpenAPI Specification 3.0, the normative statement should be interpreted in the context of the API definition language used.
