== Overview

#TODO: add more context?#

[[Requirements]]
=== Requirements for Web-based Routing

This section describes the requirements that this standard supports.

The bare minimum requirement for a Routing API is to compute a route based on a start and end point. The resulting route is encoded using the Route Exchange Model. This requirement enables implementations to work in all types of connectivity situations, including Denied, Disrupted, Intermittent, and Limited (DDIL) bandwidth communications networks.

Besides this basic requirement, additional optional requirements to the API are the following:

* Asynchronous route computation
* Support to call a webhook once the route calculation is completed
* Deletion of a computed route
* Request parts of the Route Exchange Model, e.g. only the overview

Additionally, an API may support the following optional routing parameters:

* Capability to add additional intermediate waypoints
* Select a transport mode for the route computation
* Apply a height restriction to the route computation
* Apply a load restriction to the route computation
* Ability to define obstacles that have to be avoided
* Specify departure or arrival times
