== Conformance

This Standard defines the following eight requirements and conformance classes:

* Minimal routing capability:
** <<rc_core,**Core**>>: Routing based on start/end point
* Additional API capabilities:
** <<rc_manage-routes,**Manage routes**>>: Store, fetch and delete routes stored on the server
* Additional routing parameters:
** <<rc_mode,**Modes**>>: Specify the type of transport when computing the route
** <<rc_intermediate-waypoints,**Intermediate waypoints**>>: Pass through additional points along the route
** <<rc_height,**Height restrictions**>>: Consider a specified vehicle height in meters against known height restrictions when computing the route
** <<rc_weight,**Weight restrictions**>>: Consider a specified vehicle weight in metric tons (tonnes) against known weight restrictions when computing the route
** <<rc_obstacles,**Obstacles**>>: Avoid obstacles
** <<rc_time,**Temporal constraints**>>: Specify departure/arrival time

Requirements for a single standardization target types are considered: Web API.

Conformance with this Standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC® Standard, a software implementation shall choose to implement:

* Any one of the conformance classes specified in Annex A (normative). 

Note that at all implementations must implement the Core conformance class. 

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="40,60",options="header"]
!===
|Conformance class |URI
|<<conf_core,Core>> |`\http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/core`
|<<conf_manage-routes,Manage routes>> |`\http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/manage-routes`
|<<conf_mode,Modes>> |`\http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/mode`
|<<conf_intermediate-waypoints,Intermediate waypoints>> |`\http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/intermediate-waypoints`
|<<conf_height,Height restrictions>> |`\http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/height`
|<<conf_weight,Weight restrictions>> |`\http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/weight`
|<<conf_obstacles,Obstacles>> |`\http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/obstacles`
|<<conf_time,Temporal constraints>> |`\http://www.opengis.net/spec/ogcapi-routes-1/1.0.0-draft.1/conf/time`
!===
