== Security considerations

The general Security Considerations for Web APIs are applicable to the
Routing API, too. For example, see the
link:http://www.opengis.net/doc/IS/ogcapi-features-1/1.0#_security_considerations[Security Considerations section]
in OGC API - Features - Part 1: Core.

The following is a list of topics to be considered by implementers of the API:

* Fetching the list of routes (GET `/routes`) returns information about all
routes on the server. In any operational, public deployment every user
should probably only see their routes plus routes that
others have shared with the user.
* The same applies to access to each route (GET `/route/{routeId}`) and
their definition (GET `/route/{routeId}/definition`) as well as to the
capability to cancel or delete a route (DELETE `/route/{routeId}`).

That is, any deployment that is not restricted to a closed group of users
will typically require user accounts, access control to the API operations
and a capability for sharing routes with the public or other users.
